### ISSUE TITLE
Website link

### ISSUE THREAD

**Issue by profxj** [santacruzml/santacruzml.github.io#4]
Note that the link in the README.md file
pushes people here (or at least me):

https://github.com/santacruzml/santacruzml.github.io/blob/master/santacruzml.github.io

which gives a 404 error.  I suspect this is not as intended.

**Comment by david4096** [comment]
Thanks fixed! 

https://github.com/santacruzml/santacruzml.github.io/commit/8482ce330f2952b8351c8ae4fc4720579b5d5766
